spring:
  application:
    name: tripgas
#  datasource:
#    url: jdbc:postgresql://localhost:5431/tripgas
#    username: root
#    password: 1234
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format-sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect